version: '3.8'

services:
  product-service:
    build: .
    ports:
      - "5000:80"
    environment:
      - REDIS__CONNECTIONSTRING=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
